### ISSUE TITLE
执行命令出现错误

### ISSUE THREAD

**Issue by HectorLiuk** [dsxNiubility/SXGithubPaints#1]
sudo: timestamp too far in the future: Sep 23 15:15:13 2016

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

```
while executing
```

"exec sudo date 091615002015.42"
    (file "./dsx.sh" line 33)

**Comment by dsxNiubility** [comment]
我那4个框 都是必填的， 有个是你电脑的锁屏密码，会被这边的expect使用。 你检查下

**Comment by HectorLiuk** [comment]
已经检查过了，还是不行。 装B失败...  -.-

**Comment by dsxNiubility** [comment]
sudo: timestamp too far in the future: Sep 23 15:15:13 2016    这个看来像是 你一开始试了一次不对 然后系统时间变得太早了。  你试下先恢复系统时间 然后在执行脚本
